image:
  file: .gitpod.Dockerfile

tasks:
  - name: flask Server
    init: pip3 install -r requirements.txt
    command: python3 flasky.py

  - name: frontend server
    command: >
      cd frontend &&
      npm start


ports:
  - port: 3000
    onOpen: ignore 
    visibility: public

  - port: 5000
    onOpen: open-browser
    visibility: public