@proxi=https://3000-teal-spider-53thcne1.ws-us17.gitpod.io
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYzNTc4NjI0OSwianRpIjoiMGVlNGYyY2YtYTM1ZS00YTcwLTlmMjQtMzRkZGU4OWNmZDMyIiwibmJmIjoxNjM1Nzg2MjQ5LCJ0eXBlIjoiYWNjZXNzIiwic3ViIjp7InVzZXJOYW1lIjoiSGVsaW9zIiwiZW1haWwiOiJqdW5pb3JAZ21haWwuY29tIiwiX2lkIjoiNjE2MWU1NTI2OTBkNzY0NDNlZTlkZmM1In0sImV4cCI6MTYzNTc5Mzg0OX0.HjwVtJMIrQRz-af3qM913eiSv0pA6iAYquOEdgbn7Z8
###
POST  {{proxi}}/user/signIn HTTP/1.1
content-type: application/json
 
{
    "email":"junior@gmail.com",
    "password":"castro"
}
###
POST  {{proxi}}/task/getTask HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "numberActivate":1,
    "filter":{"name":""}
}

###
POST  {{proxi}}/task/check HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "idTask":"61745c929b08479773841b46",
    "done":true
}