https://3000-a8fdd359-8631-4bc6-88ab-a414bc9b7346.ws-us04.gitpod.io/

###

POST https://3000-a8fdd359-8631-4bc6-88ab-a414bc9b7346.ws-us04.gitpod.io/user/signIn  
content-type: application/json


{
    "email": "junior@gmail.com",
    "password": "castro"
}

###
GET https://3000-a8fdd359-8631-4bc6-88ab-a414bc9b7346.ws-us03.gitpod.io/user/getUser
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYxOTY2NTM2OCwianRpIjoiYjI2Y2U5YWYtMzgyNC00MWQzLTgzNzctZWZhNTQyNWJjMzc2IiwibmJmIjoxNjE5NjY1MzY4LCJ0eXBlIjoiYWNjZXNzIiwic3ViIjp7InVzZXJOYW1lIjoiRHJhZ29uYWljb2xvc28iLCJlbWFpbCI6Imp1bmlvckBnbWFpbC5jb20ifSwiZXhwIjoxNjE5NjY2MjY4fQ.QV1ZTO1q49aLZ-TntTPUxHv4M5HGgEulhhcIDYkmfSE
